"""vitrine vendeur - banniere et logo de boutique

Revision ID: 433d5dfdc075
Revises: 9c4e2a8d6b1f
Create Date: 2026-09-13 22:26:11.257804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433d5dfdc075'
down_revision: Union[str, None] = '9c4e2a8d6b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('banner_url', sa.String(length=500), nullable=True))
    op.add_column('stores', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'logo_url')
    op.drop_column('stores', 'banner_url')
    # ### end Alembic commands ###